n-epochs: 100
batch-size: 4
# train-to-others ratio
train-split: 0.8
# val-to-test ratio
val-split: 0.5
n-workers: 2
in-shape: 224
sig-kp: 0.06
in-channels: 1
out-channels: 3
depth: 3
merge-mode: 'concat'

# augmentation
aug-rotate: 5
aug-shear: 5
aug-gaussblur: 0.02
aug-scale: 1.5

cuda: False

lr: 0.001
momentum: 0.9
