n-epochs: 100
batch-size: 4
# train-to-others ratio
train-split: 0.8
# val-to-test ratio
val-split: 0.5
n-workers: 2
in-shape: 224
sig-kp: 0.05
in-channels: 1
out-channels: 1
depth: 3
merge-mode: 'concat'

# augmentation
aug-rotate: 15
aug-shear: 15
aug-gaussblur: 0.05
aug-scale: 2.

cuda: False

lr: 0.00001
momentum: 0.9
